name: santa
description: SANTA RELEASE

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http : ^0.13.4
  flutter_webview_pro: ^3.0.1+2
  geolocator: ^8.0.5
  transition : ^2.0.2
  permission_handler: ^10.0.0
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.4
  material_design_icons_flutter: ^5.0.6595
  location: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/CI.gif
    - assets/Design.png
